# Generated by Django 5.2.8 on 2025-11-11 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoria',
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='producto',
            name='subcategoria',
            field=models.CharField(blank=True, default='Sin subcategoría', max_length=50),
        ),
        migrations.AlterField(
            model_name='combo',
            name='subcategoria',
            field=models.CharField(blank=True, default='Sin subcategoría', max_length=50),
        ),
        migrations.RenameField(
            model_name='combo',
            old_name='nombre_combo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nom_producto',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_unid',
            new_name='precio',
        ),
        migrations.AddField(
            model_name='combo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='combo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='combos/'),
        ),
        migrations.AddField(
            model_name='combo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='unidades',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='grado_alcohol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_fruto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
