# Generated by Django 5.2.7 on 2025-11-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_subcategoria_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='festividad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='combo',
            name='premium',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='combo',
            name='regalo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
