# Generated by Django 5.2.7 on 2025-11-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_combo_festividad_combo_premium_combo_regalo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='grado_alcohol',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
