# Generated by Django 5.2.7 on 2025-11-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_producto_grado_alcohol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='grado_alcohol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
