# Generated by Django 5.2.8 on 2025-11-13 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_subcategoria_categoria_and_more'),
        ('usuarios', '0002_usuario_estado_alter_usuario_rol'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carritocompra',
            options={'verbose_name': 'Carrito de compra', 'verbose_name_plural': 'Carritos de compra'},
        ),
        migrations.AlterModelOptions(
            name='cupon',
            options={'ordering': ['-fecha_expiracion']},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_pedido']},
        ),
        migrations.RemoveField(
            model_name='factura',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='precio',
        ),
        migrations.AddField(
            model_name='factura',
            name='pedido',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='ventas.pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='total_pagado',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True, default='2025-11-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carritocompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_carrito', to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='carritocompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='descuento',
            field=models.PositiveIntegerField(help_text='Porcentaje de descuento (0-100)'),
        ),
        migrations.AlterUniqueTogether(
            name='carritocompra',
            unique_together={('usuario', 'producto')},
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Item de pedido',
                'verbose_name_plural': 'Items de pedido',
            },
        ),
    ]
