# Generated by Django 5.2.7 on 2025-11-26 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_producto_grado_alcohol'),
        ('usuarios', '0003_invitacionadmin_aceptada_invitacionadmin_fecha_uso'),
        ('ventas', '0002_alter_carritocompra_options_alter_cupon_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.combo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_combos', to='usuarios.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'combo')},
            },
        ),
    ]
