# Generated by Django 5.2.7 on 2025-11-26 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_producto_grado_alcohol'),
        ('ventas', '0003_carritocombo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoitem',
            options={},
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.combo'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto'),
        ),
    ]
