# Generated by Django 5.2.7 on 2025-11-28 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_producto_grado_alcohol'),
        ('ventas', '0004_alter_pedidoitem_options_pedidoitem_combo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carritocompra',
            options={},
        ),
        migrations.RemoveField(
            model_name='factura',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='combo',
        ),
        migrations.AlterField(
            model_name='cupon',
            name='descuento',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PedidoComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.FloatField()),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.combo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_combos', to='ventas.pedido')),
            ],
        ),
    ]
