"""
Django settings for vinefresh project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os

# -------------------------
# RUTAS BASE
# -------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# -------------------------
# CONFIGURACIONES GENERALES
# -------------------------
SECRET_KEY = 'django-insecure-q*@k!qw=ub=lbgn0jal9a%99=bgg&(8zg7iy&&c!hq4_=#=v^k'
DEBUG = True
ALLOWED_HOSTS = []


# -------------------------
# APLICACIONES INSTALADAS
# -------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'usuarios',
]


# -------------------------
# MIDDLEWARE
# -------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# -------------------------
# TEMPLATES
# -------------------------
ROOT_URLCONF = 'vinefresh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.usuario_logueado',  # agregado
            ],
        },
    },
]

WSGI_APPLICATION = 'vinefresh.wsgi.application'


# -------------------------
# BASE DE DATOS
# -------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'vinefresh_db.sqlite3'),
    }
}


# -------------------------
# VALIDADORES DE CONTRASEÑAS
# -------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# -------------------------
# INTERNACIONALIZACIÓN
# -------------------------
LANGUAGE_CODE = 'es-co'  # español de Colombia 🇨🇴
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True


# -------------------------
# ARCHIVOS ESTÁTICOS
# -------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


# -------------------------
# CONFIGURACIÓN DE CORREO SMTP (GMAIL)
# -------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'danielasanchezlaraaa@gmail.com'  # tu correo Gmail
EMAIL_HOST_PASSWORD = 'yckdrkzfrmphxyst'  # tu contraseña de aplicación (sin espacios)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# -------------------------
# CLAVE PRIMARIA POR DEFECTO
# -------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
