# Generated by Django 5.2.8 on 2025-11-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_estado_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacionadmin',
            name='aceptada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitacionadmin',
            name='fecha_uso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
