# Generated by Django 5.2.7 on 2025-11-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_es_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_admin',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], default='cliente', max_length=10),
        ),
    ]
