# Generated by Django 5.2.8 on 2025-11-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_invitacionadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='solicitud_eliminacion',
            field=models.BooleanField(default=False),
        ),
    ]
