# Generated by Django 5.2.8 on 2025-11-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='asunto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
