# Generated by Django 5.2.8 on 2025-11-09 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
        ('usuarios', '0008_invitacionadmin_alter_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporte',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Resuelto', 'Resuelto')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
