# Generated by Django 5.2.8 on 2025-11-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_soporte_asunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soporte',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='asunto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
