# Generated by Django 5.2.8 on 2025-11-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0003_soporte_fecha_respuesta_soporte_respuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporte',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Resuelto', 'Resuelto'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
    ]
